# ########################
# ##### BLACK
# ########################

# [Docs root]
#   https://black.readthedocs.io/en/stable/
# [Config option reference]
#   https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#command-line-options

[tool.black]
line-length = 100

# Black will refuse to run if it's not this version.
required-version = "22.1.0"

# Ensure black's output will be compatible with all listed versions.
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']

# ########################
# ##### ISORT
# ########################

# [Docs root]
#   https://pycqa.github.io/isort/
# [Config option reference]
#   https://pycqa.github.io/isort/docs/configuration/options.html

# NOTE: File inclusion//exclusion/skip options are set at the invocation site
# and shouldn't be set in this config file.

[tool.isort]

# Ensures isort classifies imports from `dagster` as first-party in all environments. Without this
# there can be differences between buildkite and local dev.
known_first_party = ['dagster']

# Sets a variety of default options for parentheses etc that are compatible with black.
profile = "black"

# Sorts uppercase imports before lowercase improts.
case_sensitive=true

# profile=black just sets defaults, it won't read our line-length override in black's config
line_length=100

# ########################
# ##### PYLINT
# ########################

# Pylint has many options that are divvied up by category. Each [SECTION] below corresponds to a
# section in this doc:
#   https://pylint.pycqa.org/en/latest/technical_reference/features.html 

# NOTE: Running pylint in parallel (i.e. -j/--jobs option != 1) currently will not work (with
# Dagster's configuration) on some platforms (specifically macOS, maybe others). This is because of
# the `dagster.utils.linter` plugin, which contains extensions that can't be properly pickled. There
# are open issues discussing this problem but it looks like the situation is likely to persist for
# some time:
#   https://pylint.pycqa.org/en/latest/user_guide/run.html#parallel-execution
#   https://github.com/PyCQA/pylint/issues/4874

[tool.pylint.master]
ignore = ['snapshots']
py-version = 3.6
# load-plugins=dagster.utils.linter

[tool.pylint.messages-control]
disable=[
  'C',  # [category] convention-related checks
  'R',  # [category] refactoring-related checks
  'typecheck',  # [checker] redundant with mypy
  'bad-option-value',
  'bare-except',
  'broad-except',
  'duplicate-code',
  'fixme',
  'logging-format-interpolation',
  'no-init',
  'raise-missing-from',
  'redefined-outer-name',
  'unspecified-encoding'
]
>>>>>>> f6f381a25 (migrate pylint config to pyproject.toml)
